BOT_TOKEN: 
 - NDQ1MjE0MTQxMzM5MjcxMTc4.GFyr6a.4HDkQr88NRGwYOH9xcjWHi7knsMofsWSpe2U7Q
 - MTA2OTY5NDA2NjM2ODk4NzIzNw.GqYYc6.ruEefwiY4Y7bDxMEo1EvSspI4cbTPliJAiQCsU
 - MTA2OTgxNzY0OTI3MTQyNzExNQ.GAWaBt.pwpQzMlZW2CezKKDENlGQzr5cyhE7WO4WuuQUo
 - MTA3MjQ2MDgxNzgxMjk2NzQzNA.GmePyN.aVbLGmdtON-LxLZc80VhaAqzgM7PqofQ47h15w
 - ODQxNjQxNzc4NTU3MjIyOTQy.YVqlBg._gSabHLmNwesq-Ltew6nOWUaIIw
 - ODk1OTMyNDM3MTk1MDAxODU3.G-F4z-.Cm7h40VgxHrfBzZbI4iXodxi5l_wMQzCvki7KY
 - OTE5NTUxMDMzNjExNTI2MTQ0.YcKtkQ.8OaSkf1kP13dtleTEvRHgQa3N2w
 - ODQxODk3NTY5OTg1ODg4MzA2.YVsDWg.4Pc4MM4DFZCoFzYfgRc5vXj99y4
 - MTA2OTY4NzU4NjYwNTUxMDY4Ng.G0ztW8.JTFHcK2szoNGSdQjdCEqD5IN7iN5jNBexpNm9E
 - MTA3MTM3MzA5MDE5MTMxNDk5NQ.GnPBXb.rINiIYg51h_AeTUSBBUEux0cJSL9MtGRIYM4aM
CHANNEL_ID: 
 - 1030421279410495539